import type { Metadata } from "next"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import "./globals.css"
import AnnouncementBar from "@/components/AnnouncementBar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-full flex flex-col">
          <div>
            <AnnouncementBar text="This is an announcement bar" />
            <Header />
          </div>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
